version: '3.8'
services:
  transparency-proxy:
    image: transparency-proxy
    command: [ "docker-entrypoint.sh", "mitmdump", "-s", "/home/mitmproxy/issuer.py" ]
    network_mode: "host"
  transparent-policygen:
    image: transparent-policygen
    entrypoint: [ "/bin/sh" ]
    command: [ "./run.sh" ]
    network_mode: "host"
    privileged: true
    env_file:
      - ${ENV_FILE}
