$ENV:RESOURCE_GROUP="kapilv-build-rg"
$ENV:CONTAINER_REGISTRY="parmaregistry.azurecr.io"
$ENV:CONTAINER_REGISTRY_USERNAME="parmaregistry"
$ENV:CONTAINER_REGISTRY_PASSWORD="CXxMjjNUMNu3SduaLOKdVZhDiHRwOn/a"
